### ISSUE TITLE
About data set

### ISSUE THREAD

**Issue by cherryas** [ddhruvkr/Unsupervised-Style-Transfer#1]
Could you please share the PASTEL data? Thanks a lot and look forward to your reply.

**Comment by ddhruvkr** [comment]
https://github.com/dykang/PASTEL

**Comment by cherryas** [comment]
> https://github.com/dykang/PASTEL

Thank you very much.

**Comment by cherryas** [comment]
> https://github.com/dykang/PASTEL

Sorry to bother you again. Is there any training script? How to run the code?

**Comment by ddhruvkr** [comment]
You would first need to call the main.py file in the Classification folder to train the classifier. Once that is done, you can then call the main.py file in the Generator folder. You might also need to check if the data folders are correctly setup. I am sorry, for the poor documentation. I will add it in some days once I get some time.
